env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[faa0818eca74e8606a7f3ec1ba190e8db0298d43bdf5d041194797f319ac603c6383df3f188789ddae62b06a4549e1b3]"
    # bot_api: "ENCRYPTED[890d5b9d7c5fcabe7539258296ebdc053a99637accf12cc651aa958f7217a02b80f06d3a244cb8a212746ce4209b1119]"

task:
  name: Build_Upload
  timeout_in: 2h
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  chmod_script:
    - sudo chmod +x *
  # telegram_script:
    # - ./telegram
  download_script:
    - ./download_ccache
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  upload_ccache_script:
    - ./upload
