#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
repo init --depth=1 --no-repo-verify -u https://github.com/CherishOS/android_manifest.git -b test -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/hungphan2001/local_manifests --depth=1 -b lavender .repo/local_manifests
repo sync -v -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

